spring.datasource.url=jdbc:postgresql://ep-bold-mountain-ao9m9qnm.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_hgHiJC54sMoO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true